name: 'Setup Emulation'
description: |
  Install all dependencies and build docker images
  The file located at input-file must be the format described in https://github.com/Opentrons/opentrons-emulation/blob/main/README.md.
  See https://github.com/Opentrons/opentrons-emulation/tree/main/samples for examples

author: Derek Maggio
inputs:
  input-file:
    description: 'YAML or JSON system configuration'
    required: true
  cache-break:
    description: 'Specify a value here to break cache'
    required: false
    default: "default"
runs:
  using: "composite"
  steps:

    - name: Setup Emulation (Python Only)
      uses: ./.github/actions/setup-python-only
      with:
        cache-break: ${{ inputs.cache-break }}

    - name: Validate Configuration File is Remote Only
      run: make check-remote-only file_path=${{ inputs.input-file }}
      shell: bash

    - name: Build Emulation Docker Images
      run: make build file_path=${{ inputs.input-file }}
      shell: bash
