name: 'OT-3 Emulator'
description: 'Spin up emulator with specific version of firmware code'
inputs:
  ot3-firmware-commit-id:
    description: 'Full commit id in ot3-firmware to pull.'
    required: false
    default: ""
runs:
  using: 'composite'
  steps:
    - run: ./run_emulation.sh --headless --ot3-firmware-sha ${{ inputs.ot3-firmware-commit-id }}
      shell: bash
      working-directory: ${{ github.action_path }}/scripts