name: Opentrons Emulation
description: Run commands from opentrons-emulation repo
author: Derek Maggio
inputs:
  input-file:
    description: 'YAML or JSON system configuration'
    required: true
  substitutions:
    description: |
      List of lists containing substitutions you want to make to the file.
      In the format of [[service_name, property_to_replace, replacement_value], ...]
    required: false
  output-file-location:
    description: Location of output file
    required: false
  command:
    description: 'Command to run'
    required: true
  cache-break:
    description: Break the Cache
    required: false
    default: default


runs:
  using: "composite"
  steps:
    - name: Validate Command
      if: ${{ !contains(fromJson('["setup", "setup-break-cache", "setup-python-only", "run", "teardown", "yaml-sub"]'), inputs.command)}}
      run:
        exit 1
      shell: bash

    - name: Run Command
      if: inputs.command == 'run'
      uses: ./.github/actions/run
      with:
        input-file: ${{ inputs.input-file }}

    - name: Setup Command
      if: inputs.command == 'setup'
      uses: ./.github/actions/setup
      with:
        input-file: ${{ inputs.input-file }}


    - name: Setup Command (Break Cache)
      if: inputs.command == 'setup-break-cache'
      uses: ./.github/actions/setup-break-cache
      with:
        input-file: ${{ inputs.input-file }}
        cache-break: ${{ inputs.cache-break }}


    - name: Setup Command (Python Only)
      if: inputs.command == 'setup-python-only'
      uses: ./.github/actions/setup-python-only
      with:
        input-file: ${{ inputs.input-file }}
        cache-break: ${{ inputs.cache-break }}


    - name: Teardown Command
      if: inputs.command == 'teardown'
      uses: ./.github/actions/teardown
      with:
        input-file: ${{ inputs.input-file }}


    - name: YAML Sub
      if: inputs.command == 'yaml-sub'
      uses: ./.github/actions/yaml-sub
      with:
        input-file: ${{ inputs.input-file }}
        output-file-location: ${{ inputs.output-file-location }}
        substitutions: ${{ inputs.substitutions }}
