version: '3.8'
services:
  echo-prod:
    build:
      context: .
      target: ot3-firmware-echo
    container_name: echo-prod
    network_mode: host
    tty: true

  heater-shaker-prod:
    build:
      context: .
      target: heater-shaker
    container_name: heater-shaker-prod
    network_mode: host
    tty: true
