version: '3.8'
services:
  ot3-echo-dev:
    image: ot3-echo-dev:latest
    build:
      context: .
      target: ot3-firmware-echo-dev
    container_name: ot3-echo-dev
    network_mode: host
    tty: true
    volumes:
      - ${OT3_FIRMWARE_DIRECTORY}:/ot3-firmware
      - ./entrypoint.sh:/entrypoint.sh

  heater-shaker-dev:
    image: heater-shaker-dev:latest
    build:
      context: .
      target: heater-shaker-dev
    container_name: heater-shaker-dev
    network_mode: host
    tty: true
    volumes:
      - ${OPENTRONS_MODULES_DIRECTORY}:/opentrons-modules
      - ./entrypoint.sh:/entrypoint.sh
