name: 'Setup Emulation (Python Only)'
description: |
  Install all dependencies
  The file located at input-file must be the format described in https://github.com/Opentrons/opentrons-emulation/blob/main/README.md.
  See https://github.com/Opentrons/opentrons-emulation/tree/main/samples for examples

author: Derek Maggio
inputs:
  cache-break:
    description: 'Specify a value here to break cache'
    required: false
    default: "default"
runs:
  using: "composite"
  steps:

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Cache Python Dependencies
      uses: actions/cache@v2
      id: python-cache
      with:
        path: |
          ~/work/opentrons-emulation/opentrons-emulation/.venv
          ~/work/opentrons-emulation/opentrons-emulation/emulation_system/.venv
        key: ${{ runner.os }}-pipenv-${{ hashFiles('./emulation_system/Pipfile.lock') }}-${{ hashFiles('./Pipfile.lock') }}-${{ hashFiles('./Makefile') }}-${{ inputs.cache-break }}

    - name: Install Pipenv
      run: pip install pipenv==2022.3.24
      shell: bash

    - name: Setup repo
      if: steps.python-cache.outputs.cache-hit != 'true'
      run: make setup
      env:
        PIPENV_VENV_IN_PROJECT: enabled
      shell: bash
