name: 'Setup Emulation (Python Only)'
description: |
  Install all dependencies
  The file located at input-file must be the format described in https://github.com/Opentrons/opentrons-emulation/blob/main/README.md.
  See https://github.com/Opentrons/opentrons-emulation/tree/main/samples for examples

author: Derek Maggio
inputs:
  cache-break:
    description: 'Specify a value here to break cache'
    required: false
    default: "default"
runs:
  using: "composite"
  steps:

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: pipenv
        cache-dependency-path: |
          ./emulation_system/Pipfile.lock
          ./Pipfile.lock
          ./Makefile

    - name: Install Pipenv
      run: pip install pipenv==2022.3.24
      shell: bash

    - name: Setup repo
      run: make setup
      shell: bash
