name: 'Run Emulation'
description: |
  Run emulated robot based off of passed input-file parameter.
  The file located at input-file must be the format described in https://github.com/Opentrons/opentrons-emulation/blob/main/README.md.
  See https://github.com/Opentrons/opentrons-emulation/tree/main/samples for examples

author: Derek Maggio
inputs:
  input-file:
    description: 'YAML or JSON system configuration'
    required: true
  python-version:
    description: 'Version of python to install'
    required: false
    default: "3.10"
  cache-break:
    description: 'Specify a value here to break cache'
    required: false
    default: "default"
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Cache Python Dependencies
      uses: actions/cache@v2
      with:
        path: "~/.local/share/virtualenvs/**"
        key: ${{ runner.os }}-python-${{ inputs.python-version }}-pipenv-${{ hashFiles('./emulation_system/Pipfile.lock') }}-${{ inputs.cache-break }}

    - name: Setup repo
      run: |
        pip install pipenv
        make setup
      shell: bash

    - name: Create configuration.json
      run: cp configuration_ci.json configuration.json
      shell: bash

    - name: Validate Configuration File is Remote Only
      run: make check-remote-only file_path=${{ inputs.input-file }}
      shell: bash

    - name: Build Emulation Docker Images
      run: make em-build-amd64 file_path=${{ inputs.input-file }}
      shell: bash

    - name: Run Emulation Docker System
      run: make em-run-detached file_path=${{ inputs.input-file }}
      shell: bash
