# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'json'

settings = JSON.parse(File.read(File.join(File.dirname(__FILE__), 'settings.json')))

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"

  settings['SHARED_FOLDERS'].each do |conf|
  	config.vm.synced_folder conf['host_path'], conf['vm_path']
  end

  settings['SHARED_FOLDERS'].each do |conf|
  	config.vm.synced_folder conf['host_path'], conf['vm_path']
  end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = settings['VM_MEMORY']
    vb.cpus = settings['VM_CPUS']
  end

  config.vm.provision "packages",
  name: "packages",
  type: "shell",
  path: "provisioning_scripts/packages.sh"

  config.vm.provision "docker",
  name: "docker",
  type: "shell",
  path: "provisioning_scripts/docker.sh"

end
