name: 'Teardown Emulation'
description: 'Bring down docker container emulation'
author: Derek Maggio
inputs:
  input-file:
    description: 'YAML or JSON system configuration'
    required: true
runs:
  using: "composite"
  steps:
    - name: Run
      run: make em-remove file_path=${{ inputs.input-file }}
      shell: bash
