name: 'Run Emulation'
description: |
  Run emulated robot based off of passed input-file parameter.
  The file located at input-file must be the format described in https://github.com/Opentrons/opentrons-emulation/blob/main/README.md.
  See https://github.com/Opentrons/opentrons-emulation/tree/main/samples for examples

author: Derek Maggio
inputs:
  input-file:
    description: 'YAML or JSON system configuration'
    required: true
runs:
  using: "composite"
  steps:

    - name: Run Emulation Docker System
      run: make run-detached file_path=${{ inputs.input-file }}
      shell: bash
