# Workflow to verify that yaml-substitution are working correctly.

name: "YAML Substitution Sanity Check"

on:
  push:
    branches:
      - 'main'
      - 'release-*'
  pull_request:
    paths:
      - 'emulation_system/**'
      - '.github/workflows/yaml-sub-sanity-check.yaml'
      - '.github/actions/**'
      - 'action.yaml'
      - 'scripts/makefile/helper_scripts/**'
      - 'docker/**'
      - './Makefile'
  workflow_dispatch:
    inputs:
      cache-break:
        description: Break the Cache
        required: false
        default: default

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  yaml-sub-sanity-check:
    runs-on: "ubuntu-20.04"
    name: YAML Substitution Sanity Check
    steps:
      - name: Checkout opentrons-emulation
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}

      # Only change `main` in Opentrons/opentrons-emulation@main
      # if making changes to .github/actions or action.yaml
      - name: Setup Emulation
        uses: Opentrons/opentrons-emulation@main
        with:
          cache-break: ${{ github.event.inputs.cache-break }}
          command: setup-python-only

      - name: Add yq package
        run: pip3 install yq

      # Only change `main` in Opentrons/opentrons-emulation@main
      # if making changes to .github/actions or action.yaml
      - name: YAML Substitution
        uses: Opentrons/opentrons-emulation@main
        with:
          command: yaml-sub
          substitutions: >-
            [
              ["exposed-port", "5000", "otie"],
              ["monorepo-source", "test"]
            ]
          input-file: ${{ github.workspace }}/samples/ot3/ot3_remote.yaml
          output-file-location: ${{ github.workspace }}/output.yaml

      - name: Get first sub value
        id: first-sub
        run: echo "FIRST=$(yq -r '.robot."exposed-port"' ${{ github.workspace }}/output.yaml)" >> $GITHUB_OUTPUT

      - name: Get second sub value
        id: second-sub
        run: echo "SECOND=$(yq -r '."monorepo-source"' ${{ github.workspace }}/output.yaml)" >> $GITHUB_OUTPUT

      - name: Confirm Values 1
        if: ${{ steps.first-sub.outputs.FIRST != '5000' }}
        run: |
          echo "First Sub - ${{ steps.first-sub.outputs.FIRST }}"
          exit 1

      - name: Confirm Values 2
        if: ${{ steps.second-sub.outputs.SECOND != 'test' }}
        run: |
          echo "Second Sub - ${{ steps.second-sub.outputs.SECOND }}"
          exit 1
