version: '3.8'
services:
  emulator-proxy-local:
    image: emulator-proxy-local:latest
    build:
      context: .
      target: emulator-proxy-local
    container_name: emulator-proxy-local
    ports:
      - '8000-8005:8000-8005'
      - '9000-9005:9000-9005'
    environment:
      OT_EMULATOR_magdeck_proxy: '{"emulator_port": 8000, "driver_port": 9000}'
      OT_EMULATOR_temperature_proxy: '{"emulator_port": 8001, "driver_port": 9001}'
      OT_EMULATOR_thermocycler_proxy: '{"emulator_port": 8002, "driver_port": 9002}'
    volumes:
      - "./entrypoint.sh:/entrypoint.sh"
      - ${OPENTRONS_DIRECTORY}:/opentrons
    networks:
      - local

    tty: true

  magdeck-firmware-local:
    image: magdeck-firmware-local:latest
    build:
      context: .
      target: magdeck-firmware-local
    container_name: magdeck-firmware-local
    environment:
      OT_EMULATOR_magdeck_proxy: '{"emulator_port": 8000, "driver_port": 9000}'
    depends_on:
      - 'emulator-proxy-local'
    volumes:
      - "./entrypoint.sh:/entrypoint.sh"
      - ${OPENTRONS_DIRECTORY}:/opentrons
    networks:
      - local
    tty: true

  tempdeck-firmware-local:
    image: tempdeck-firmware-local:latest
    build:
      context: .
      target: tempdeck-firmware-local
    container_name: tempdeck-firmware-local
    environment:
      OT_EMULATOR_temperature_proxy: '{"emulator_port": 8001, "driver_port": 9001}'
    depends_on:
      - 'emulator-proxy-local'
    volumes:
      - "./entrypoint.sh:/entrypoint.sh"
      - ${OPENTRONS_DIRECTORY}:/opentrons
    networks:
      - local
    tty: true

  thermocycler-firmware-local:
    image: thermocycler-firmware-local:latest
    build:
      context: .
      target: thermocycler-firmware-local
    container_name: thermocycler-firmware-local
    environment:
      OT_EMULATOR_thermocycler_proxy: '{"emulator_port": 8002, "driver_port": 9002}'
    depends_on:
      - 'emulator-proxy-local'
    volumes:
      - "./entrypoint.sh:/entrypoint.sh"
      - ${OPENTRONS_DIRECTORY}:/opentrons
    networks:
      - local
    tty: true

networks:
  local:
