version: '3.8'
services:
  emulator-proxy-remote:
    image: emulator-proxy-remote:latest
    build:
      context: .
      target: emulator-proxy-remote
    container_name: emulator-proxy-remote
    environment:
      OT_EMULATOR_smoothie: '{"port": 11000}'
      OT_EMULATOR_magdeck_proxy: '{"emulator_port": 10001, "driver_port": 11001}'
      OT_EMULATOR_temperature_proxy: '{"emulator_port": 10002, "driver_port": 11002}'
      OT_EMULATOR_thermocycler_proxy: '{"emulator_port": 10003, "driver_port": 11003}'
      OT_EMULATOR_heatershaker_proxy_proxy: '{"emulator_port": 10004, "driver_port": 11004}'
    networks:
      - local
    tty: true

  robot-server:
    image: robot-server-remote:lastest
    build:
      context: .
      target: robot-server-remote
    container_name: robot-server-remote
    ports:
      - '31950:31950'
    environment:
      OT_SMOOTHIE_EMULATOR_URI: socket://emulator-proxy-remote:11000
      OT_EMULATOR_module_server: '{"host": "emulator-proxy-remote"}'
    networks:
      - local
    depends_on:
      - 'emulator-proxy-remote'

  magdeck-firmware-1:
    image: magdeck-firmware-remote:latest
    build:
      context: .
      target: magdeck-firmware-remote
    container_name: magdeck-firmware-1
    environment:
      OT_EMULATOR_magdeck_proxy: '{"emulator_port": 10001, "driver_port": 11001}'
      OT_EMULATOR_magdeck: '{"serial_number": "magdeck-1", "model":"mag_deck_v20", "version":"2.0.0"}'
    command: [ "emulator-proxy-remote" ]
    networks:
      - local
    depends_on:
      - 'emulator-proxy-remote'
    tty: true

  magdeck-firmware-2:
    image: magdeck-firmware-remote:latest
    build:
      context: .
      target: magdeck-firmware-remote
    container_name: magdeck-firmware-2
    environment:
      OT_EMULATOR_magdeck_proxy: '{"emulator_port": 10001, "driver_port": 11001}'
      OT_EMULATOR_magdeck: '{"serial_number": "magdeck-2", "model":"mag_deck_v20", "version":"2.0.0"}'
    command: [ "emulator-proxy-remote" ]
    networks:
      - local
    depends_on:
      - 'emulator-proxy-remote'
    tty: true

  tempdeck-firmware-remote:
    image: tempdeck-firmware-remote:latest
    build:
      context: .
      target: tempdeck-firmware-remote
    container_name: tempdeck-firmware-remote
    environment:
      OT_EMULATOR_temperature_proxy: '{"emulator_port": 10002, "driver_port": 11002}'
    command: [ "emulator-proxy-remote" ]
    networks:
      - local
    depends_on:
      - 'emulator-proxy-remote'
    tty: true

  thermocycler-firmware-remote:
    image: thermocycler-firmware-remote:latest
    build:
      context: .
      target: thermocycler-firmware-remote
    container_name: thermocycler-firmware-remote
    environment:
      OT_EMULATOR_thermocycler_proxy: '{"emulator_port": 10003, "driver_port": 11003}'
    command: [ "emulator-proxy-remote" ]
    networks:
      - local
    depends_on:
      - 'emulator-proxy-remote'
    tty: true
networks:
  local:
