version: '3.8'
services:
  emulator-proxy-dev:
    image: emulator-proxy-dev:latest
    build:
      context: .
      target: emulator-proxy-dev
    container_name: emulator-proxy-dev
    ports:
      - '8000-8005:8000-8005'
      - '9000-9005:9000-9005'
    environment:
      OT_EMULATOR_magdeck_proxy: '{"emulator_port": 8000, "driver_port": 9000}'
      OT_EMULATOR_temperature_proxy: '{"emulator_port": 8001, "driver_port": 9001}'
      OT_EMULATOR_thermocycler_proxy: '{"emulator_port": 8002, "driver_port": 9002}'
    volumes:
      - "./entrypoint.sh:/entrypoint.sh"
      - ${OPENTRONS_DIRECTORY}:/opentrons

    tty: true

  magdeck-driver-dev:
    image: magdeck-driver-dev:latest
    build:
      context: .
      target: magdeck-driver-dev
    container_name: magdeck-driver-dev
    environment:
      OT_EMULATOR_magdeck_proxy: '{"emulator_port": 8000, "driver_port": 9000}'
    links:
      - 'emulator-proxy-dev'
    depends_on:
      - 'emulator-proxy-dev'
    volumes:
      - "./entrypoint.sh:/entrypoint.sh"
      - ${OPENTRONS_DIRECTORY}:/opentrons
    tty: true

  tempdeck-driver-dev:
    image: tempdeck-driver-dev:latest
    build:
      context: .
      target: tempdeck-driver-dev
    container_name: tempdeck-driver-dev
    environment:
      OT_EMULATOR_temperature_proxy: '{"emulator_port": 8001, "driver_port": 9001}'
    links:
      - 'emulator-proxy-dev'
    depends_on:
      - 'emulator-proxy-dev'
    volumes:
      - "./entrypoint.sh:/entrypoint.sh"
      - ${OPENTRONS_DIRECTORY}:/opentrons
    tty: true

  thermocycler-driver-dev:
    image: thermocycler-driver-dev:latest
    build:
      context: .
      target: thermocycler-driver-dev
    container_name: thermocycler-driver-dev
    environment:
      OT_EMULATOR_thermocycler_proxy: '{"emulator_port": 8002, "driver_port": 9002}'
    links:
      - 'emulator-proxy-dev'
    depends_on:
      - 'emulator-proxy-dev'
    volumes:
      - "./entrypoint.sh:/entrypoint.sh"
      - ${OPENTRONS_DIRECTORY}:/opentrons
    tty: true