version: '3.8'
services:
  ot3-echo-prod:
    image: ot3-echo-prod:latest
    build:
      context: .
      target: ot3-firmware-echo
    container_name: ot3-echo-prod
    network_mode: host
    tty: true

  heater-shaker-prod:
    image: heater-shaker-prod:latest
    build:
      context: .
      target: heater-shaker
    container_name: heater-shaker-prod
    network_mode: host
    command: ["--socket", "http://${HEATER_SHAKER_SOCKET_HOST}:${HEATER_SHAKER_SOCKET_PORT}"]
    tty: true
