name: "build-devcontainer"
on: # Make sure the devcontainer changes are pushed on changes to main
  push:
    branches:
      - main
      - "233-devcontainer"
    paths:
      - ".devcontainer/*"

concurrency: # One run of this workflow per branch.
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.2
        with:
          imageName: ghcr.io/opentrons/opentrons-emulation-devcontainer
          runCmd: |
            python --version
