# This workflow runs test and lint on branch pushes that touch the
# emulation-system project

name: 'emulation-system Lint & Test'

on:
  # Most of the time, we run on pull requests, which lets us handle external PRs
  push:
    paths:
      - 'emulation_system/**'
      - 'opentrons-emulation'
      - '.github/workflows/emulation-system-lint-test.yaml'
    tags-ignore:
      - '*'
  pull_request:
    paths:
      - 'emulation_system/**'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  lint-test:
    name: 'emulation-system linting and tests'
    runs-on: 'ubuntu-18.04'
    steps:
      - name: "Checkout Repo"
        uses: 'actions/checkout@v2'
        with:
          node-version: '12'

      - name: "Setup Python"
        uses: 'actions/setup-python@v2'
        with:
          python-version: '3.7'

      - name: Cache Python Dependencies
        uses: actions/cache@v2
        with:
          path: "~/.local/share/virtualenvs/**"
          key: ${{ runner.os }}-pipenv-${{ hashFiles('./emulation_system/Pipfile.lock') }}-${{ inputs.cache-break }}

      - name: "Setup Project"
        run: |
        pip install pipenv
        make setup

      - name: "Lint"
        run: make lint

      - name: "Test"
        run: make test

      - name: 'Upload Coverage Report'
        uses: 'codecov/codecov-action@v2'
        with:
          files: ./g-code-testing/coverage.xml
          flags: g-code-testing
