# This workflow runs test and lint on branch pushes that touch the
# emulation-system project.

name: 'emulation-system Lint & Test'

on:
  push:
    branches:
      - 'main'
      - 'release-*'
  pull_request:
    paths:
      - 'emulation_system/**'
      - '.github/workflows/emulation-system-lint-test.yaml'
      - './Makefile'
      - '*.md'
  workflow_dispatch:
    inputs:
      cache-break:
        description: Break the Cache
        required: false
        default: default

defaults:
  run:
    shell: bash

jobs:
  lint-test:
    name: 'emulation-system linting and tests'
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Checkout opentrons-emulation repository
        uses: actions/checkout@v3
        with:
          ref: "RQA-258-fix-ot3-emulation-not-starting"

      - name: Setup Emulation
        uses: Opentrons/opentrons-emulation@RQA-258-fix-ot3-emulation-not-starting
        with:
          cache-break: ${{ github.event.inputs.cache-break }}
          command: setup-python-only

      - name: "Lint"
        run: make lint

      - name: "Test"
        run: make test

      - name: 'Upload Coverage Report'
        uses: 'codecov/codecov-action@v2'
        with:
          files: ./g-code-testing/coverage.xml
          flags: g-code-testing
