# This workflow runs test and lint on branch pushes that touch the
# emulation-system project.

name: 'emulation-system Lint & Test'

on:
  push:
    paths:
      - 'emulation_system/**'
      - '.github/workflows/emulation-system-lint-test.yaml'
    branches:
      - 'main'
      - 'release'
  pull_request:
    paths:
      - 'emulation_system/**'
      - '.github/workflows/emulation-system-lint-test.yaml'
  workflow_dispatch:
    inputs:
      cache-break:
        description: Break the Cache
        required: false
        default: default

defaults:
  run:
    shell: bash

jobs:
  lint-test:
    name: 'emulation-system linting and tests'
    runs-on: 'ubuntu-18.04'
    steps:
      - name: "Checkout Repo"
        uses: 'actions/checkout@v2'

      - name: "Setup Python"
        uses: 'actions/setup-python@v2'
        with:
          python-version: '3.10'

      - name: Cache Python Dependencies
        uses: actions/cache@v2
        with:
          path: "~/.local/share/virtualenvs/**"
          key: ${{ runner.os }}-pipenv-${{ hashFiles('./emulation_system/Pipfile.lock') }}-${{ hashFiles('./Pipfile.lock') }}-${{ hashFiles('./Makefile') }}-${{ inputs.cache-break }}

      - name: "Setup Project"
        run: |
          pip install pipenv==2022.3.24
          make setup

      - name: "Lint"
        run: make lint

      - name: "Test"
        run: make test

      - name: 'Upload Coverage Report'
        uses: 'codecov/codecov-action@v2'
        with:
          files: ./g-code-testing/coverage.xml
          flags: g-code-testing
