on: [ pull_request, push ]

jobs:
  ot3-emulator-sanity-check:
    strategy:
      matrix:
        file: [
          'ot2/ot2_with_all_modules.yaml',
          'ot3/ot3_remote.yaml',
        ]
    runs-on: "ubuntu-18.04"
    name: OT-3 Emulation Sanity Check (${{ matrix.file }})
    steps:
      - name: Checkout opentrons-emulation
        uses: actions/checkout@v2

      - name: Setup Emulation
        uses: ./.github/actions/run_emulation
        with:
          input-file: ${PWD}/samples/${{ matrix.file }}
          python-version: 3.7

      - name: Give it some time
        run: sleep 10s

      - name: Test Emulation
        run: "curl --request GET --header 'opentrons-version: *' http://localhost:31950/modules"

      - name: Teardown Emulation
        uses: ./.github/actions/teardown_emulation
        with:
          input-file: ${PWD}/samples/${{ matrix.file }}
