# Workflow to verify that repo's emulation actions are working correctly.

name: "Opentrons Emulation Github Action Tests"

on:
  push:
    branches:
      - 'main'
      - 'release-*'
  pull_request:
    paths:
      - 'emulation_system/**'
      - '.github/workflows/repo-action-validation.yaml'
      - '.github/actions/**'
      - 'action.yaml'
      - 'scripts/makefile/helper_scripts/**'
      - 'docker/**'
      - './Makefile'
  workflow_dispatch:
    inputs:
      cache-break:
        description: Break the Cache
        required: false
        default: default

jobs:
  opentrons-emulation-sanity-check:
    strategy:
      matrix:
        file: [
          'ot2/ot2_with_all_modules.yaml',
          'ot3/ot3_remote.yaml',
        ]
    runs-on: "ubuntu-20.04"
    name: Opentrons Emulation Sanity Check (${{ matrix.file }})
    steps:

      - name: Checkout opentrons-emulation
        uses: actions/checkout@v3
        with:
          ref: "RQA-258-fix-ot3-emulation-not-starting"

      - name: Setup Emulation
        uses: Opentrons/opentrons-emulation@RQA-258-fix-ot3-emulation-not-starting
        with:
          input-file: ${PWD}/samples/${{ matrix.file }}
          cache-break: ${{ github.event.inputs.cache-break }}
          command: setup

      - name: Run Emulation
        uses: Opentrons/opentrons-emulation@RQA-258-fix-ot3-emulation-not-starting
        with:
          input-file: ${PWD}/samples/${{ matrix.file }}
          command: run

      - name: Give it some time to start up
        run: sleep 10s

      - name: Test Emulation
        run: "curl --request GET --header 'opentrons-version: *' http://localhost:31950/modules"

      - name: Teardown Emulation
        uses: Opentrons/opentrons-emulation@RQA-258-fix-ot3-emulation-not-starting
        with:
          input-file: ${PWD}/samples/${{ matrix.file }}
          command: teardown
