# Workflow to verify that repo's emulation actions are working correctly.

name: "Run Hardware Tests"

on:
  push:
    branches:
      - 'main'
      - 'release-*'
  pull_request:
    paths:
      - '.github/workflows/run-hardware-tests.yaml'
      - '.github/actions/**'
      - 'action.yaml'
      - 'docker/**'
      - './Makefile'
  schedule:
    # Running at 1:37 AM, so we don't get delays from so many people running nightly actions at midnight/top of hour
    - cron: '37 1 * * 1-5'
  workflow_dispatch:
    inputs:
      cache-break:
        description: Break the Cache
        required: false
        default: default

jobs:
  run-hardware-tests:
    runs-on: "ubuntu-18.04"
    name: Run Hardware Tests
    steps:

      - name: Checkout opentrons-emulation repository
        uses: actions/checkout@v3
        with:
          ref: "ghcr-image-caching"

      - name: Checkout monorepo
        uses: actions/checkout@v3
        with:
          repository: "Opentrons/opentrons"
          path: opentrons

      - name: Setup Python for opentrons repository
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Setup opentrons-emulation project
        uses: Opentrons/opentrons-emulation@ghcr-image-caching
        with:
          input-file: ${PWD}/samples/ot3/ot3_remote.yaml
          cache-break: ${{ inputs.cache-break }}
          command: setup

      - name: Cache Python Dependencies
        uses: actions/cache@v2
        id: python-cache
        with:
          path: "~/.local/share/virtualenvs/**"
          key: ${{ runner.os }}-${{ hashFiles('./opentrons/hardware/Pipfile.lock') }}-${{ inputs.cache-break }}

      - name: Setup hardware project in opentrons repository
        if: steps.python-cache.outputs.cache-hit != 'true'
        run: make setup
        working-directory: ./opentrons/hardware

      - name: Run emulated system
        uses: Opentrons/opentrons-emulation@ghcr-image-caching
        with:
          input-file: ${PWD}/samples/ot3/ot3_remote.yaml
          command: run

      - name: Run hardware project integration tests
        run: make test-with-opentrons-sock-emulator
        working-directory: ./opentrons/hardware

      - name: Teardown emulation
        uses: Opentrons/opentrons-emulation@ghcr-image-caching
        with:
          input-file: ${PWD}/samples/ot3/ot3_remote.yaml
          command: teardown

      - name: Send results notification
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.EMULATION_NIGHTLY_TESTING_SLACK_WEBHOOK }}
          SLACK_USERNAME: "OT-3 Integration Tests Results"
          SLACK_TITLE: Test Run Results
          SLACK_MESSAGE: ${{ job.status }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON_EMOJI: ':rocket:'
