# Workflow to upload Docker Image Bases to Github Container Registry

name: "Upload Docker Image Bases"

on:
  push:
    branches:
      - 'main'
      - 'release-*'
      - 'multi-arch-*'  ### REMOVE THIS BEFORE MERGING ###
    tags:
      - 'v**'
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Install QEMU emulators
        run: docker run -i --rm --privileged tonistiigi/binfmt --install all

      - name: Create and use multi-platform builder
        run: docker buildx create --name emulation_builder --platform linux/arm64,linux/amd64 --driver docker-container --bootstrap --use

      - name: Build and push images
        run: make push-docker-image-bases branch_name="${{ github.ref_name }}"
