name: 'Setup Emulation (Python Only)'
description: |
  Install all dependencies
  The file located at input-file must be the format described in https://github.com/Opentrons/opentrons-emulation/blob/main/README.md.
  See https://github.com/Opentrons/opentrons-emulation/tree/main/samples for examples

author: Derek Maggio
inputs:
  cache-break:
    description: 'Specify a value here to break cache'
    required: false
    default: "default"
  cache-dir:
    description: Location of cache dir
    required: false
    default: ${{ github.workspace }}
runs:
  using: "composite"
  steps:

    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python3 -
      shell: bash

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: poetry
        cache-dependency-path: |
          ${{ inputs.cache-dir }}/emulation_system/poetry.lock
          ${{ inputs.cache-dir }}/emulation_system/Makefile
          ${{ inputs.cache-dir }}/Makefile

    - name: Setup repo
      run: make setup
      working-directory: ${{ inputs.cache-dir }}
      shell: bash
